# HTTP (Tomcat) port
spring:
   config:
     activate:
        on-profile: local
   application:
     name: unlimits_client
server:
  port: 1001
# Configure this Discovery Server
eureka:
  client: #Not a client
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
---
spring:
   config:
     activate:
        on-profile: develop
   application:
     name: unlimits_client
# HTTP (Tomcat) port
server:
  port: 1002  
# Configure this Discovery Server
eureka:
  client: #Not a client
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
---
spring:
   config:
     activate:
        on-profile: stage
   application:
     name: unlimits_client
# HTTP (Tomcat) port
server:
  port: 1003  
# Configure this Discovery Server
eureka:
  client: #Not a client
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/